pool.go

There was a panic because we're accessing `resp` when it's `nil`.

fix: panic in pool.go

---

caboose.go
pool.go

retry failed requests

---

caboose.go
pool.go

fix #13 
When deployed in `bifrost-gateway` we should include {`x-fetcher`: `bifrost-gateway/<version>`} to indicate to backing nodes what is requesting

allow specification of extra headers on backing requests

---

pool.go

This changes the logging level of block requests to debug and removes the `fmt.Println`.

fix: change block level logs to debug

---

pool.go

Ensure the request to saturn uses the context and doesn't keep running if the upstream context has been canceled.

fix: request honours upstream context

---

pool.go

This makes debugging possible without recompiling.

fix: log error per pop

---

pool.go

re-find idx in lock

---

caboose.go
cmd/caboose/main.go
failure_test.go
pool.go

This PR aims to land https://github.com/filecoin-saturn/caboose/pull/19 and make some changes on top of it. 
The main changes include:
- Take care of `slowly re-fill the reputation of down-weighted backends as they successfully return content` TODO in https://github.com/filecoin-saturn/caboose/pull/19. The way we do this is by bumping up the weights of downvoted nodes that successfully return content by 20 percent on every success with a debounce until they hit the default weight of 20 that we assign to all nodes.
- Addresses @lidel 's comment at https://github.com/filecoin-saturn/caboose/pull/19#discussion_r1105843807 by ensuring we timeout requests to the Saturn L1s with a reasonable default.
- I want to make some changes around how we refresh the pool after getting back a list of …

 Fix bugs, refactor, document and land the weighted consistent hashing branch

---

pool.go

report these even in error cases

add latency / size metrics for error cases

---

caboose.go
cmd/caboose/main.go
failure_test.go
log.go
pool.go

Fixes https://github.com/filecoin-saturn/caboose/issues/38.

Send correct logs to Saturn logger 

---

caboose.go
metrics.go
pool.go

fixes https://github.com/filecoin-saturn/caboose/issues/34

Revamp caboose metrics

---

pool.go

Ttfb should not be negative

---

caboose.go
caboose_test.go
failure_test.go
pool.go

Cool down cid failures

---

caboose.go
caboose_test.go
failure_test.go
pool.go
pool_test.go

We need to downvote votes more gradually so that they get time to recover from temporary failures, Lassie timeouts, from being overloaded etc. but without them getting in the way of fetch requests However, once we remove a node from the pool post the gradual downvoting, we should make the node earn it's reputation back before we start sending more requests to it. To that end, this PR:
-  Introduces the concept of freezing/cooling down fetches from a node in the face of 429s/transient errors so nodes can get some time to recover instead of us trying them repeatedly and then downvoting them. However, there is a limit to how often we will cool down a node post which we will start downvoting/removing it.
- In my local testing using apache backend, I noticed that a number of Saturn Nodes …

Better downvoting and cool down fetches

---

caboose.go
failure_test.go
fetcher.go
pool.go

Removes the `RetryAfter` property from `ErrSaturnTooManyRequests` and `ErrCidCoolDown` and wraps them with `gateway.ErrRetryAfter`.

feat: common .RetryAfter() interface for errors

---

fetcher.go
go.mod
go.sum

* add a timing metric for each caboose request around fetches when a timing key is present on the context
* forwards with a tag any timing keys in the response of the request onto the context timing key

forwards server timings up to context

---

fetcher.go
metrics.go
pool.go

Some refactor/fixes of the metrics code for correctness/grokability/dryness
Add more dimensions/labels to metrics to better capture block/car, cache-hit/cache-miss  cases
Record prometheus metrics around important L1 server-timings

Metrics Refactor and record metrics around L1 Server-Timings

---

caboose.go
fetcher.go
go.mod
go.sum
metrics.go
pool.go
pool_test.go

Record Peer latency & speed distribution & record with accurate car size fetch buckets

---

fetcher.go

in response to https://github.com/filecoin-saturn/caboose/pull/79#pullrequestreview-1373282919

limit metric cardinality for errors

---

fetcher.go
metrics.go
pool.go
pool_test.go

- Only look at ttfb for cache hits for understanding peer latency distribution.
- Only look at ttfb & speed of peers who have served a certain  threshold of successful retrievals.
- Better buckets for latency dist histogram.

Fix latency distribution metrics

---

caboose.go
fetcher.go
metrics.go
pool.go

1. We do have some peers with a reasonable P75 latency  even after they have served >100 successful cache hit retrievals
https://protocollabs.grafana.net/d/6g0_YjBVk/bifrost-caboose-staging?orgId=1&from=now-6h&to=now&editPanel=32
2. Even after the context cancellation fix by @willscott in https://github.com/filecoin-saturn/caboose/pull/82, a significant number of requests(for both blocks and CARs) still fail with the context cancelled error.  Let's instrument them more to help Bifrost debug this.
https://protocollabs.grafana.net/d/6g0_YjBVk/bifrost-caboose-staging?orgId=1&from=now-6h&to=now&editPanel=30

More instrumentation of context cancellations and reward low latency nodes

---

caboose.go
fetcher.go
go.mod
tracing.go

Adds Open Telemetry tracing spans. Context: https://github.com/ipfs/bifrost-gateway/issues/68#issuecomment-1504921191.
This is not necessarily required. On the screenshot below you see the tracing result from the Bifrost Gateway up until the HTTP request Caboose makes to the Saturn node. What this PR adds is the `Caboose.*` trace spans. The HTTP GET already worked.
@lidel @willscott not sure where is the most value to put the spans here, but this seems like a good start. Feel free to add/remove some.

feat: open telemetry tracing

---

metrics.go
tieredhashing/tiered_hashing.go
tieredhashing/tiered_hashing_test.go

Even if we're not able to fill the pool of main set nodes, we should still fill as many as we can. This will help if some nodes have been kicked out of the main set for correctness for example.

Upgrade as many nodes as we can to the main tier even if we don't have enough

---

caboose.go
caboose_test.go
fetcher.go
metrics.go
pool.go
pool_metrics.go
pool_refresh_test.go
tieredhashing/tiered_hashing.go
tieredhashing/tiered_hashing_test.go

- Add back the nodes we've kicked out if they're the only option we have to fill the pool. However, do it in descending order of reputation as determined by the orchestrator.
-  Let's plot CAR response size vs TTFB to visualise the co-relation there if any.
- Let's use a `CLIENT_ENV` header instead of `User-Agent` for debugging/metrics on L1s.

Prevent pool starvation during duress and record CAR response size vs TTFB

---

tieredhashing/tiered_hashing.go

These are simply forbidden because of bad bits.

No-penalise-403s

---

caboose.go

An explicit error for signaling that the wrong data was returned

Add ErrInvalidResponse

---

version.json

Update to version to `0.0.3` to update the compliance cid work. 
@willscott seeing that https://pkg.go.dev/github.com/filecoin-saturn/caboose has the current version as 0.0.2 so updating to 0.0.3

feat: update caboose version

---

fetcher.go

Including header sizes in response size makes it hard to do byte-for-byte comparisons between different services sending the same CAR file.

report size of response body only, exclude headers

---

fetcher.go

Do not drain responses at all so go-routines don't get blocked.

Do not drain responses 2

---

pool.go

We're not really making `format=raw` reqs with mime type CAR so fixing that here.

compliance cids should look like normal reqs

---

pool.go
pool_refresh_test.go
tieredhashing/config.go
tieredhashing/tiered_hashing.go
tieredhashing/tiered_hashing_test.go

We don't want to evict nodes if their correctness is similar to other nodes even if their absolute correctness is below a certain random threshold as software bugs can cause absolute correctness to dip which will result in us evicting legit nodes.

Relative correctness policy in Caboose

---

caboose.go
pool.go
tieredhashing/tiered_hashing.go

Need to investigate high error rate in mirrored requests. Have added logging here for that.

Increase mirrored requests and prevent main set from starvation during DDOS

---

tieredhashing/tiered_hashing.go

Now that mirroring is actually working, we can increase pool size and afford to have more unknown nodes in the pool as we will test them with a good cadence and promote them to main if they do better than what we have in main.

Increase pool size now that mirroring is actually working

---

caboose.go
fetcher.go

Improve retry logic

---

fetcher.go
metrics.go
pool.go
pool_metrics.go

Removes metrics we no longer need as the backpressure PR has landed in main and some of those metrics were put in place to catch old bugs that no longer exist.

Removed unused metrics

---

fetcher.go

should allow for validation in tracing ux

convert l1 timing headers into otel spans

---

fetcher.go
tieredhashing/tiered_hashing.go

the configured orchestrator url will also need to be updated in infra, but this will take a 'core' attribute when present on a node and propagate it to the submitted trace for relevant sub requests

Add a core attribute to tracing span
